In [1]:
import pandas as pd
import numpy as np

In [33]:
lego = pd.read_csv(r"C:\Users\varia\OneDrive\Dragon Hoard's Index\Datasets\LEGO BE100 Index.csv")
lego = lego.dropna()

In [27]:
lego.head(10)

,itemurl,itemid,itemname,itemyear,itemmonth,itemday,itemprice_lowerbound,itemprice_lower,itemprice_upper,itemprice_upperbound,datetime
0,https://www.brickeconomy.com/set/375-2/lego-ca...,375-2,lego-castle,2017,5,1,5832.00,6156.00,7128.00,7776.00,2017-5-1
1,https://www.brickeconomy.com/set/375-2/lego-ca...,375-2,lego-castle,2017,6,1,6645.51,6895.61,7645.90,8146.10,2017-6-1
2,https://www.brickeconomy.com/set/375-2/lego-ca...,375-2,lego-castle,2017,7,1,7074.25,7467.26,8646.30,9432.33,2017-7-1
3,https://www.brickeconomy.com/set/375-2/lego-ca...,375-2,lego-castle,2017,8,1,8380.12,8695.50,9641.64,10272.40,2017-8-1
4,https://www.brickeconomy.com/set/375-2/lego-ca...,375-2,lego-castle,2017,9,1,8545.35,9020.10,10444.32,11393.81,2017-9-1
5,https://www.brickeconomy.com/set/375-2/lego-ca...,375-2,lego-castle,2017,10,1,9542.95,9902.09,10979.52,11697.81,2017-10-1
6,https://www.brickeconomy.com/set/375-2/lego-ca...,375-2,lego-castle,2017,11,1,9674.66,10212.14,11824.58,12899.54,2017-11-1
7,https://www.brickeconomy.com/set/375-2/lego-ca...,375-2,lego-castle,2018,0,1,8972.87,9310.55,10323.62,10999.00,2018-0-1
8,https://www.brickeconomy.com/set/375-2/lego-ca...,375-2,lego-castle,2018,1,1,8617.23,9095.96,10532.17,11489.64,2018-1-1
9,https://www.brickeconomy.com/set/375-2/lego-ca...,375-2,lego-castle,2018,2,1,8484.05,8803.35,9761.22,10399.81,2018-2-1

In [20]:
name_list = lego['itemname'].drop_duplicates()
id_list = lego['itemid'].drop_duplicates()
print(f'{len(name_list)}, {len(id_list)}')

92, 94

In [21]:
print(type(lego.iloc[0,3]))

<class 'numpy.float64'>

In [34]:
lego['itemyear'] = lego['itemyear'].astype(int).astype(str)
lego['itemmonth'] = (lego['itemmonth']+1).astype(int).astype(str)
lego['itemday'] = lego['itemday'].astype(int).astype(str)

lego['datetime'] = lego['itemyear'] + '-' + lego['itemmonth'] + '-' + lego['itemday']
lego['datetime'] = pd.to_datetime(lego['datetime'])

In [36]:
lego['price_avg'] = (lego['itemprice_lower'] + lego['itemprice_upper'])/2

In [37]:
df = pd.DataFrame()

for item in id_list:
    # Get temp df with only data of specific id
    temp_df = lego[lego['itemid'] == str(item)].copy()
    price = temp_df.groupby('datetime')['price_avg'].mean().sort_index()
    df = df.join(price.rename(str(item)), how = 'outer')

In [42]:
df = df.round(2)
df.tail()

,375-2,497-1,10182-1,10196-1,10195-1,6071-1,10185-1,10019-1,7783-1,10212-1,...,9465-1,3182-1,79003-1,10218-1,21304-1,21306-1,92176-1,7417-1,70788-1,40391-1
datetime,,,,,,,,,,,,,,,,,,,,,
2025-10-01,10752.00,6064.08,4374.20,3627.12,3271.10,2964.00,2629.96,2504.93,1937.38,2218.26,...,507.62,469.56,422.78,421.04,353.83,350.01,284.91,330.71,176.42,60.85
2025-11-01,12522.56,5840.16,4319.32,3876.34,3376.82,2970.12,2653.30,2602.74,1710.22,2057.58,...,497.32,454.76,410.11,391.06,346.30,332.99,291.23,312.20,197.04,51.34
2025-12-01,13210.77,6794.58,4497.29,3699.28,3765.66,2543.21,2727.14,2220.89,1705.06,2136.65,...,474.78,501.52,437.29,418.77,358.40,353.68,302.09,338.18,163.49,46.92
2026-01-01,12610.61,5699.37,4910.82,3632.56,3971.77,2520.56,2552.94,2425.10,1861.84,2523.23,...,543.40,406.32,430.19,400.60,345.72,349.02,307.96,260.30,206.04,46.84
2026-02-01,11758.64,6048.14,3935.52,4666.00,4194.12,2158.27,2565.75,3057.62,2063.12,2703.78,...,546.49,450.24,438.37,458.34,354.08,357.51,336.02,216.80,199.96,45.82

In [43]:
df.to_csv('BE100 Index.csv')